# Creating, Reading and Writing with Pandas

Based on the Kaggle tutorial: https://www.kaggle.com/code/residentmario/creating-reading-and-writing

This notebook covers:
- Creating DataFrames and Series from scratch
- Reading data from CSV and Excel files
- Writing data to CSV files
- Basic DataFrame inspection

## Imports

In [1]:
import pandas as pd

## Creating a DataFrame

A DataFrame is a table. It contains an array of individual entries, each of which has a certain value. Each entry corresponds to a row (or record) and a column.

The most common way to create a DataFrame is from a Python dictionary.

In [2]:
# Create a DataFrame from a dictionary
# Keys become column names, values become column data
df = pd.DataFrame({'Yes': [50, 21], 'No': [131, 2]})
df

   Yes   No
0   50  131
1   21    2

In [3]:
# DataFrame entries can be strings too
df_strings = pd.DataFrame({
    'Bob': ['I liked it.', 'It was awful.'],
    'Sue': ['Pretty good.', 'Bland.']
})
df_strings

             Bob           Sue
0    I liked it.  Pretty good.
1  It was awful.        Bland.

In [4]:
# Use the index parameter to set custom row labels
df_indexed = pd.DataFrame(
    {'Bob': ['I liked it.', 'It was awful.'], 'Sue': ['Pretty good.', 'Bland.']},
    index=['Product A', 'Product B']
)
df_indexed

                     Bob           Sue
Product A    I liked it.  Pretty good.
Product B  It was awful.        Bland.

## Creating a Series

A Series is a sequence of data values — essentially a single column of a DataFrame.
You can create a Series from a list.

In [5]:
# Create a Series from a list
s = pd.Series([1, 2, 3, 4, 5])
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [6]:
# A Series is essentially a single column of a DataFrame
# You can assign a name and custom index
s_named = pd.Series(
    [30, 35, 40],
    index=['2015 Sales', '2016 Sales', '2017 Sales'],
    name='Product A'
)
s_named

2015 Sales    30
2016 Sales    35
2017 Sales    40
Name: Product A, dtype: int64

## Reading Data Files

Being able to create a DataFrame is handy. But, most of the time, we won't actually be creating our own data by hand. Instead, we'll be working with data that already exists.

Data can be stored in any of a number of different forms and formats. By far the most basic of these is the humble CSV file.

In [7]:
# First, let's create a sample CSV file to work with
import io

csv_data = """country,variety,points,price
Italy,White Blend,87,16
Portugal,Portuguese White,87,15
US,Pinot Gris,87,14
US,Riesling,87,11
Spain,Nerello Mascalese,87,11
Italy,Nerello Mascalese,87,40
France,Rosé,88,15
Germany,Riesling,88,12
Argentina,Malbec,88,20
US,Cabernet Sauvignon,88,65
"""

with open('/tmp/wine_reviews.csv', 'w') as f:
    f.write(csv_data)

print("Sample CSV file created at /tmp/wine_reviews.csv")

Sample CSV file created at /tmp/wine_reviews.csv

In [8]:
# Read a CSV file using pd.read_csv()
wine_reviews = pd.read_csv('/tmp/wine_reviews.csv')
wine_reviews

     country             variety  points  price
0      Italy         White Blend      87     16
1   Portugal   Portuguese White      87     15
2         US          Pinot Gris      87     14
3         US            Riesling      87     11
4      Spain   Nerello Mascalese      87     11
5      Italy   Nerello Mascalese      87     40
6     France                Rosé      88     15
7    Germany            Riesling      88     12
8  Argentina              Malbec      88     20
9         US  Cabernet Sauvignon      88     65

In [9]:
# Use index_col to set one of the columns as the row index
wine_reviews_indexed = pd.read_csv('/tmp/wine_reviews.csv', index_col=0)
wine_reviews_indexed

                    variety  points  price
country
Italy           White Blend      87     16
Portugal  Portuguese White      87     15
US              Pinot Gris      87     14
US                Riesling      87     11
Spain    Nerello Mascalese      87     11
Italy    Nerello Mascalese      87     40
France                Rosé      88     15
Germany           Riesling      88     12
Argentina           Malbec      88     20
US       Cabernet Sauvignon      88     65

## Inspecting a DataFrame

Once you have a DataFrame, you'll want to get a quick sense of what it looks like.

In [10]:
# shape returns a tuple of (rows, columns)
wine_reviews.shape

(10, 4)

In [11]:
# head() returns the first 5 rows by default
wine_reviews.head()

     country            variety  points  price
0      Italy        White Blend      87     16
1   Portugal  Portuguese White      87     15
2         US         Pinot Gris      87     14
3         US           Riesling      87     11
4      Spain  Nerello Mascalese      87     11

In [12]:
# dtypes shows the data type of each column
wine_reviews.dtypes

country    object
variety    object
points      int64
price       int64
dtype: object

In [13]:
# info() provides a concise summary of the DataFrame
wine_reviews.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   country  10 non-null     object
 1   variety  10 non-null     object
 2   points   10 non-null     int64
 3   price    10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

## Accessing Data

There are two primary methods for accessing data in a DataFrame:
- **`loc`** – label-based selection
- **`iloc`** – integer position-based selection

In [14]:
# Access a column by name
wine_reviews['country']

0        Italy
1     Portugal
2           US
3           US
4        Spain
5        Italy
6       France
7      Germany
8    Argentina
9           US
Name: country, dtype: object

In [15]:
# iloc selects by integer position (like Python list indexing)
# Select the first row
wine_reviews.iloc[0]

country         Italy
variety    White Blend
points              87
price               16
Name: 0, dtype: object

In [16]:
# iloc with [row, column] indexing
# Select the value in row 0, column 0
wine_reviews.iloc[0, 0]

'Italy'

In [17]:
# Select the first column using iloc
wine_reviews.iloc[:, 0]

0        Italy
1     Portugal
2           US
3           US
4        Spain
5        Italy
6       France
7      Germany
8    Argentina
9           US
Name: country, dtype: object

In [18]:
# loc selects by label
# Select row 0 using loc
wine_reviews.loc[0, 'country']

'Italy'

In [19]:
# loc is useful for selecting specific columns by name across all rows
wine_reviews.loc[:, ['country', 'variety']]

     country             variety
0      Italy         White Blend
1   Portugal   Portuguese White
2         US          Pinot Gris
3         US            Riesling
4      Spain   Nerello Mascalese
5      Italy   Nerello Mascalese
6     France                Rosé
7    Germany            Riesling
8  Argentina              Malbec
9         US  Cabernet Sauvignon

## Writing Data Files

You can save a DataFrame to a CSV file using the `to_csv()` method.
Set `index=False` to avoid writing the row index as an extra column.

In [20]:
# Write a DataFrame to a CSV file
wine_reviews.to_csv('/tmp/wine_reviews_out.csv', index=False)
print("DataFrame saved to /tmp/wine_reviews_out.csv")

DataFrame saved to /tmp/wine_reviews_out.csv

In [21]:
# Verify the file was written correctly by reading it back
verify_df = pd.read_csv('/tmp/wine_reviews_out.csv')
verify_df.head()

     country            variety  points  price
0      Italy        White Blend      87     16
1   Portugal  Portuguese White      87     15
2         US         Pinot Gris      87     14
3         US           Riesling      87     11
4      Spain  Nerello Mascalese      87     11

## Summary

| Task | Method |
|------|--------|
| Create DataFrame from dict | `pd.DataFrame({'col': [values]})` |
| Create a Series | `pd.Series([values], name='name')` |
| Read CSV | `pd.read_csv('file.csv')` |
| Read CSV with index column | `pd.read_csv('file.csv', index_col=0)` |
| Inspect shape | `df.shape` |
| Preview first rows | `df.head()` |
| Check data types | `df.dtypes` |
| Select by position | `df.iloc[row, col]` |
| Select by label | `df.loc[row, 'col']` |
| Write to CSV | `df.to_csv('file.csv', index=False)` |